[package]
name = "letsroll"
version = "0.1.0"
authors = ["moussetc <moussetc@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.6.1"
docopt = "1"
serde = "1.0" 
serde_derive = "1.0"